data:extend{
    {
        type="field",
        name="forest",
        display_name="Forest",
        resource=data.raw.resource["wood"]
    },
    {
        type="field",
        name="grass-field",
        display_name="Grass Field",
        resource=data.raw.resource["cow"]
    },
    {
        type="field",
        name="mountain",
        display_name="Mountain",
        resource=data.raw.resource["ore"]
    },
    {
        type="field",
        name="mine",
        display_name="Mine",
        resource=data.raw.resource["brick"]
    },
    {
        type="field",
        name="field",
        display_name="Field",
        resource=data.raw.resource["buckwheat"]
    },
    {
        type="field",
        name="desert",
        display_name="Desert"
    }
}
