data:extend{
    {
        type="resource",
        name="wood",
        display_name="Les"
    },
    {
        type="resource",
        name="ore",
        display_name="Ruda"
    },
    {
        type="resource",
        name="cow",
        display_name="Krava"
    },
    {
        type="resource",
        name="buckwheat",
        display_name="Ajda"
    },
    {
        type="resource",
        name="victory-point",
        display_name="Zmagovalna točka"
    }
}
