data:extend{
    {
        type="resource",
        name="wood",
        display_name="Wood"
    },
    {
        type="resource",
        name="ore",
        display_name="Ore"
    },
    {
        type="resource",
        name="brick",
        display_name="Brick"
    },
    {
        type="resource",
        name="cow",
        display_name="Cow"
    },
    {
        type="resource",
        name="buckwheat",
        display_name="Buckwheat"
    },
    {
        type="resource",
        name="victory-point",
        display_name="Victory Point"
    }
}
